[cursor]
unfocused_hollow = true
thickness = 0.15

[cursor.style]
shape = "Block"

[window]
decorations = "None"
opacity = 0.75
dynamic_padding = true

[window.padding]
x = 5
y = 5

[scrolling]
history = 10000
multiplier = 3

[colors.primary]
background = "#15191d"
foreground = "#f8f8f0"


[font]
size = 10

normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }
